# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose_mysql.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(192, 113)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.mysql_host = QtWidgets.QLineEdit(Form)
        self.mysql_host.setObjectName("mysql_host")
        self.gridLayout.addWidget(self.mysql_host, 0, 1, 1, 1)
        self.mysql_user = QtWidgets.QLineEdit(Form)
        self.mysql_user.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.mysql_user.setObjectName("mysql_user")
        self.gridLayout.addWidget(self.mysql_user, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.mysql_password = QtWidgets.QLineEdit(Form)
        self.mysql_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mysql_password.setObjectName("mysql_password")
        self.gridLayout.addWidget(self.mysql_password, 2, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.mysql_host, self.mysql_user)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MySQL登录"))
        self.label_2.setText(_translate("Form", "主机地址"))
        self.pushButton.setText(_translate("Form", "登录"))
        self.label.setText(_translate("Form", "MySQL用户"))
        self.pushButton_2.setText(_translate("Form", "注册"))
        self.label_3.setText(_translate("Form", "MySQL密码"))
